# .github/workflows/run-script.yml
name: Run algo-01 script

on:
  schedule:
    - cron: "* * * * *" # alle 2 Minuten
  workflow_dispatch: # erlaubt manuelles Triggern

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run script
        run: |
          python algo-01.py
